test: all
	java Program00_2017 -24 ggh \"Hello world\" 56

all: Program00_2017.class

Program00_2017.class: Program00_2017.java
	javac Program00_2017.java

clean:
	rm -f Program00_2017.class

PHONY: all clean